# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a938e94c1a787e889c48704e6268f90031fc7a006b94d660040a5d1e605b94ca6d97dab0a5981b2e8b284f031ea72775880267369c9a7c859015dc895baa21a

test:
  secret_key_base: 052702a23add5e59f60cd1863e6a7de87b04471e23813708887be84da9d034f1f7488fa7c84bb72c7fef6ab1f74ae9021540b9f763fb1cbefe11585e689aa178

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
